# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7416d31be70761d020af8fdfa808a47bab770adf886239e59b73d58b263dbe6f3c2764a86939b4dbb8f50d9eff7a1cc89407c1dc35a9da035751e44aa1e46bd4

test:
  secret_key_base: b00037016e3c03a9f3dc3cc254e5ec9be87d3d703d5a89884d0c7149ac835f894453511d9311adef18754b72f03340002ca065b3a91bd8c0c9f8c621d4239a70

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
